### ISSUE TITLE
Wrong feature name in documentaion

### ISSUE THREAD

**Issue by yutannihilation** [dimforge/rapier#26]
In [Getting Started page](https://rapier.rs/docs/user_guides/rust/getting_started/), `simd_nightly` is specified, but I think this should be `simd-nightly`.

``` toml
[dependencies]
# TODO: Replace the * by the latest version number.
rapier2d = { version = "*", features = [ "simd_nightly", "parallel" ] }
```
