### ISSUE TITLE
Zero restitution coefficient but still bouncy

### ISSUE THREAD

**Issue by nahaharo** [dimforge/rapier#420]
I set the restitution coefficient as 0, but the blocks are still bouncy.

The more important thing is colliding between two rigid bodies, which have zero restitution coefficient resulting more bouncy situation.

I checked with a different program (https://physion.net/), but this shows no bounce on the second block.

Is this error, or should I fix my code?

Here is my code.

main.rs
```rust
use bevy::prelude::*;
use bevy_rapier2d::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_plugin(RapierPhysicsPlugin::<NoUserData>::pixels_per_meter(100.0))
        .add_startup_system(create)
        .run();
}
fn create(mut commands: Commands) {
    commands.spawn(Camera2dBundle::default());
    commands.spawn((
        Collider::cuboid(150., 100. / 2.),
        SpriteBundle {
            sprite: Sprite {
                color: Color::rgb(0.5, 0.5, 0.5),
                custom_size: Some(Vec2::new(300., 100.)),
                ..default()
            },
            transform: Transform::from_xyz(0., -200., 0.0),
            ..default()
        },
        Restitution {
            coefficient: 0.,
            combine_rule: CoefficientCombineRule::Multiply,
        },
        RigidBody::Fixed,
    ));

    commands.spawn((
        Collider::cuboid(150., 100. / 2.),
        SpriteBundle {
            sprite: Sprite {
                color: Color::rgb(0.5, 0.5, 0.5),
                custom_size: Some(Vec2::new(300., 100.)),
                ..default()
            },
            transform: Transform::from_xyz(0., 200., 0.0),
            ..default()
        },
        Restitution {
            coefficient: 0.,
            combine_rule: CoefficientCombineRule::Multiply,
        },
        RigidBody::Dynamic,
    ));

    commands.spawn((
        Collider::cuboid(150., 100. / 2.),
        SpriteBundle {
            sprite: Sprite {
                color: Color::rgb(0.5, 0.5, 0.5),
                custom_size: Some(Vec2::new(300., 100.)),
                ..default()
            },
            transform: Transform::from_xyz(0., 800., 0.0),
            ..default()
        },
        Restitution {
            coefficient: 0.,
            combine_rule: CoefficientCombineRule::Multiply,
        },
        RigidBody::Dynamic,
    ));
}
```

cargo.toml
```toml
[package]
name = "Test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = "0.9" # make sure this is the latest version
bevy_rapier2d = {version="0.19", features=["enhanced-determinism"]}
```
