### ISSUE TITLE
Does determinism work with `bevy_rapier2d` in wasm?

### ISSUE THREAD

**Issue by romdotdog** [dimforge/rapier#514]
This is my `Cargo.toml`:
```toml
[package]
name = ""
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.11"
bevy_rapier2d = { version = "0.22", features = ["enhanced-determinism"] }

[profile.dev]
opt-level = "z"
debug = false

[profile.dev.package.rapier2d]
opt-level = 3
```

`main.rs`:
```rs
use bevy::{prelude::*, sprite::MaterialMesh2dBundle};
use bevy_rapier2d::prelude::*;

fn main() {
    App::new()
        .insert_resource(ClearColor(Color::rgb_u8(111, 182, 246)))
        .add_plugins(DefaultPlugins)
        .add_plugins(RapierPhysicsPlugin::<NoUserData>::pixels_per_meter(100.0))
        .add_systems(Startup, setup)
        .run();
}

fn setup(mut commands: Commands, mut meshes: ResMut<Assets<Mesh>>, mut materials: ResMut<Assets<ColorMaterial>>) {
    commands
        .spawn(Collider::cuboid(500.0, 100.0))
        .insert(MaterialMesh2dBundle {
            mesh: meshes
                .add(shape::Quad::new(Vec2::new(1000., 200.)).into())
                .into(),
            material: materials.add(ColorMaterial::from(Color::rgb(0.5, 0.5, 0.5))),
            transform: Transform::from_xyz(0.0, -250.0, 0.0),
            ..default()
        });

        
    commands
        .spawn(RigidBody::Dynamic)
        .insert(Collider::cuboid(10.0, 10.0))
        .insert(Restitution::coefficient(0.7))
        .insert(MaterialMesh2dBundle {
            mesh: meshes
                .add(shape::Quad::new(Vec2::new(20., 20.)).into())
                .into(),
            material: materials.add(ColorMaterial::from(Color::RED)),
            transform: Transform::from_xyz(0.0, 400.0, 0.0),
            ..default()
        });

    commands.spawn(Camera2dBundle::default());
}
```

I'm compiling for `wasm32-unknown-unknown` and using `wasm-server-runner` to host. If you refresh the page, the cube takes a different trajectory each time. Is there something wrong with my code?
