### ISSUE TITLE
egui puffin profiler customization

### ISSUE THREAD

**Issue by ThierryBerger** [dimforge/rapier#760]
`unstable-puffin-pr-235` highlights by default the profiling section relevant to rapier and its testbed.

- #743 merged  the feature `unstable-puffin-pr-235`
- This issue serves as documentation and tracks a path to stabilization.

- [ ] We 're effectively blocked by https://github.com/EmbarkStudios/puffin/pull/235 to stabilize.

In the meantime, you can enable these lines from the workspace `Cargo.toml` (commented on `master`):
```toml
# For feature unstable-puffin-pr-235
puffin_egui = { version = "0.29", optional = true, git = "https://github.com/Vrixyz/puffin.git", branch = "expose_ui_options" }
puffin = { version = "0.19", optional = true, git = "https://github.com/Vrixyz/puffin.git", branch = "expose_ui_options" }
# 
```
